version: '3.8'

services:
  backend:
    build:
      context: ./tug-of-war-backend
      dockerfile: Dockerfile
    container_name: tug-of-war-backend
    ports:
      - "3000:3000"
    networks:
      - tug-of-war-network
    restart: unless-stopped

  frontend:
    build:
      context: ./tug-of-war-frontend
      dockerfile: Dockerfile
    container_name: tug-of-war-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tug-of-war-network
    restart: unless-stopped

networks:
  tug-of-war-network:
    driver: bridge
